sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.0"
  - "4.1"
  - "4.2"
  - "5"
  - "6"
  - "7"
  - "8"
  - "iojs"
before_script:
  - npm uninstall grunt # https://github.com/npm/npm/issues/3958
matrix:
  fast_finish: true
